import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { SessionStoreProvider } from "./providers/session-store-provider";
import { Navbar } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionStoreProvider>
          <Navbar />
          {children}
        </SessionStoreProvider>
      </body>
    </html>
  );
}
